version: 2.1



orbs:
  common: radar/common@1.0
  node: radar/node@1.0

run_tests: &run_tests
  working_directory: ~/project
  steps:
  - checkout
  - common/setup-gcp-gcr
  - common/install-docker-compose
  - node/install
  - run:
      name: Setup Integration Environment
      command: |
        source ~/.bashrc
        scripts/simnet-setup.sh ci
  - run:
      name: Setup Environment Variables
      command: cp .env.test .env
  - run: 
      name: Run Tests
      command: yarn test

jobs:
  lint:
    docker:
    - image: circleci/node:10
    working_directory: ~/project
    steps:
    - checkout
    - run: 
        name: Run Linter
        command: yarn lint
  audit:
    docker:
    - image: circleci/node:10
    working_directory: ~/project
    steps:
    - checkout
    - run: 
        name: Run Audit
        command: yarn audit
  test-node-8:
    docker:
    - image: circleci/node:8
    <<: *run_tests
  test-node-10:
    docker:
    - image: circleci/node:10
    <<: *run_tests
  test-node-11:
    docker:
    - image: circleci/node:11
    <<: *run_tests

workflows:
  version: 2
  default:
    jobs:
      - lint
      # - audit
      - test-node-8
      - test-node-10
      - test-node-11
